wiki/web/forms.py
"""
    Forms
    ~~~~~
"""
from flask_wtf import Form
from wtforms import BooleanField
from wtforms import TextField
from wtforms import TextAreaField
from wtforms import PasswordField
from wtforms.validators import InputRequired
from wtforms.validators import ValidationError

from wiki.core import clean_url
from wiki.web import current_wiki
from wiki.web import current_users


class URLForm(Form):
    url = TextField('', [InputRequired()])

    def validate_url(form, field):
        if current_wiki.exists(field.data):
            raise ValidationError('The URL "%s" exists already.' % field.data)

    def clean_url(self, url):
        return clean_url(url)


class SearchForm(Form):
    term = TextField('', [InputRequired()])
    ignore_case = BooleanField(
        description='Ignore Case',
        # FIXME: default is not correctly populated
        default=True)


class EditorForm(Form):
    title = TextField('', [InputRequired()])
    body = TextAreaField('', [InputRequired()])
    tags = TextField('')


class LoginForm(Form):
    name = TextField('', [InputRequired()])
    password = PasswordField('', [InputRequired()])

    def validate_name(form, field):
        user = current_users.get_user(field.data)
        if not user:
            raise ValidationError('This username does not exist.')

    def validate_password(form, field):
        user = current_users.get_user(form.name.data)
        if not user:
            return
        if not user.check_password(field.data):
            raise ValidationError('Username and password do not match.')

wiki/web/__init__.py
import os

from flask import current_app
from flask import Flask
from flask import g
from flask_login import LoginManager
from werkzeug.local import LocalProxy

from wiki.core import Wiki
from wiki.web.user import UserManager

class WikiError(Exception):
    pass

def get_wiki():
    wiki = getattr(g, '_wiki', None)
    if wiki is None:
        wiki = g._wiki = Wiki(current_app.config['CONTENT_DIR'])
    return wiki

current_wiki = LocalProxy(get_wiki)

def get_users():
    users = getattr(g, '_users', None)
    if users is None:
        users = g._users = UserManager(current_app.config['CONTENT_DIR'])
    return users

current_users = LocalProxy(get_users)


def create_app(directory):
    app = Flask(__name__)
    app.config['CONTENT_DIR'] = directory
    app.config['TITLE'] = u'wiki'
    try:
        app.config.from_pyfile(
            os.path.join(app.config.get('CONTENT_DIR'), 'config.py')
        )
    except IOError:
        msg = "You need to place a config.py in your content directory."
        raise WikiError(msg)

    loginmanager.init_app(app)

    from wiki.web.routes import bp
    app.register_blueprint(bp)

    return app


loginmanager = LoginManager()
loginmanager.login_view = 'wiki.user_login'

@loginmanager.user_loader
def load_user(name):
    return current_users.get_user(name)

wiki/web/routes.py
"""
    Routes
    ~~~~~~
"""
from flask import Blueprint
from flask import flash
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from flask_login import current_user
from flask_login import login_required
from flask_login import login_user
from flask_login import logout_user

from wiki.core import Processor
from wiki.web.forms import EditorForm
from wiki.web.forms import LoginForm
from wiki.web.forms import SearchForm
from wiki.web.forms import URLForm
from wiki.web import current_wiki
from wiki.web import current_users
from wiki.web.user import protect


bp = Blueprint('wiki', __name__)


@bp.route('/')
@protect
def home():
    page = current_wiki.get('home')
    if page:
        return display('home')
    return render_template('home.html')


@bp.route('/index/')
@protect
def index():
    pages = current_wiki.index()
    return render_template('index.html', pages=pages)


@bp.route('/<path:url>/')
@protect
def display(url):
    page = current_wiki.get_or_404(url)
    return render_template('page.html', page=page)


@bp.route('/create/', methods=['GET', 'POST'])
@protect
def create():
    form = URLForm()
    if form.validate_on_submit():
        return redirect(url_for(
            'wiki.edit', url=form.clean_url(form.url.data)))
    return render_template('create.html', form=form)


@bp.route('/edit/<path:url>/', methods=['GET', 'POST'])
@protect
def edit(url):
    page = current_wiki.get(url)
    form = EditorForm(obj=page)
    if form.validate_on_submit():
        if not page:
            page = current_wiki.get_bare(url)
        form.populate_obj(page)
        page.save()
        flash('"%s" was saved.' % page.title, 'success')
        return redirect(url_for('wiki.display', url=url))
    return render_template('editor.html', form=form, page=page)


@bp.route('/preview/', methods=['POST'])
@protect
def preview():
    data = {}
    processor = Processor(request.form['body'])
    data['html'], data['body'], data['meta'] = processor.process()
    return data['html']


@bp.route('/move/<path:url>/', methods=['GET', 'POST'])
@protect
def move(url):
    page = current_wiki.get_or_404(url)
    form = URLForm(obj=page)
    if form.validate_on_submit():
        newurl = form.url.data
        current_wiki.move(url, newurl)
        return redirect(url_for('wiki.display', url=newurl))
    return render_template('move.html', form=form, page=page)


@bp.route('/delete/<path:url>/')
@protect
def delete(url):
    page = current_wiki.get_or_404(url)
    current_wiki.delete(url)
    flash('Page "%s" was deleted.' % page.title, 'success')
    return redirect(url_for('wiki.home'))


@bp.route('/tags/')
@protect
def tags():
    tags = current_wiki.get_tags()
    return render_template('tags.html', tags=tags)


@bp.route('/tag/<string:name>/')
@protect
def tag(name):
    tagged = current_wiki.index_by_tag(name)
    return render_template('tag.html', pages=tagged, tag=name)


@bp.route('/search/', methods=['GET', 'POST'])
@protect
def search():
    form = SearchForm()
    if form.validate_on_submit():
        results = current_wiki.search(form.term.data, form.ignore_case.data)
        return render_template('search.html', form=form,
                               results=results, search=form.term.data)
    return render_template('search.html', form=form, search=None)


@bp.route('/user/login/', methods=['GET', 'POST'])
def user_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = current_users.get_user(form.name.data)
        login_user(user)
        user.set('authenticated', True)
        flash('Login successful.', 'success')
        return redirect(request.args.get("next") or url_for('wiki.index'))
    return render_template('login.html', form=form)


@bp.route('/user/logout/')
@login_required
def user_logout():
    current_user.set('authenticated', False)
    logout_user()
    flash('Logout successful.', 'success')
    return redirect(url_for('wiki.index'))


@bp.route('/user/')
def user_index():
    pass


@bp.route('/user/create/')
def user_create():
    pass


@bp.route('/user/<int:user_id>/')
def user_admin(user_id):
    pass


@bp.route('/user/delete/<int:user_id>/')
def user_delete(user_id):
    pass


"""
    Error Handlers
    ~~~~~~~~~~~~~~
"""


@bp.errorhandler(404)
def page_not_found(error):
    return render_template('404.html'), 404

wiki/web/templates/base.html
{% from "helpers.html" import input %}
<!DOCTYPE html>
<html>
	<head>
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap.css') }}">
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='responsive.css') }}">
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='pygments.css') }}">
	</head>

	<body>
		<div class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<div class="row">
						<div class="span12">
							<a href="#" class="brand">{{ config.TITLE }}</a>
							<ul class="nav">
								<li><a href="{{ url_for('wiki.home') }}">Home</a></li>
								<li><a href="{{ url_for('wiki.index') }}">Index</a></li>
								<li><a href="{{ url_for('wiki.tags') }}">Tags</a></li>
								<li><a href="{{ url_for('wiki.search') }}">Search</a></li>
								<li class="divider-vertical"></li>
								<li><a href="{{ url_for('wiki.create') }}">New Page</a></li>
								<li class="divider-vertical"></li>
								<li></li>
							</ul>

							<ul class="nav pull-right">
								{% if current_user.is_anonymous %}
									<li><a href="{{ url_for('wiki.user_login') }}">Login</a></li>
								{% else %}
									<li><a href="{{ url_for('wiki.user_logout') }}">Logout</a></li>
								{% endif %}
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="container">
			<div class="row">
				<div class="span10 offset1">
					{% block header %}
						<div class="page-header">
							<h1>{% block title %}{{ page.title }}{% endblock title %}</h1>
						</div>
					{% endblock header %}
				</div>
			</div>
			<div class="row">
				<div class="span7 offset1">
					{% with messages = get_flashed_messages(with_categories=True) %}
						{% if messages %}
							{% for category, message in messages %}
								<div class="alert alert-{{ category }}">
									<button type="button" class="close" data-dismiss="alert">&times;</button>
									{{ message }}
								</div>
							{% endfor %}
						{% endif %}
					{% endwith %}
					{% if form and form.errors %}
						<div class="alert alert-error">Errors occured verifying your input. Please check the marked fields below.</div>
					{% endif %}
					{% block content %}
					{% endblock content %}
				</div>
				<div class="span3">
					{% block sidebar %}
					{% endblock sidebar %}
				</div>
			</div>
		</div>
		<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.9.0/jquery.min.js "></script>
		<script type="text/javascript">
			if (typeof jQuery == 'undefined') {
				document.write(unescape("%3Cscript src='{{ url_for('static', filename='jquery.min.js') }}' type='text/javascript'%3E%3C/script%3E"));
			}
		</script>
		<script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
		<script type="text/javascript">
			{% block postscripts %}
			{% endblock postscripts %}
		</script>
	</body>
</html>

wiki/web/templates/create.html
{% extends "base.html" %}

{% block title %}Create a new page{% endblock title %}
{% block content %}
<form method="POST" class="form-inline">
	{{ form.hidden_tag() }}
	{{ input(form.url, placeholder="URL of the new page", autocomplete="off") }}
	<input type="submit" class="btn btn-success" value="Create">
</form>
{% endblock content %}

{% block sidebar %}
<p class="alert alert-success">Thank you for creating new content!</p>
{% endblock sidebar %}

wiki/web/templates/editor.html
{% extends "base.html" %}

{% block title -%}
Wiki Editor
{%- endblock title %}

{% block content %}
<ul class="nav nav-tabs">
	<li class="active"><a href="#editor" data-toggle="tab">Editor</a></li>
	<li><a href="#preview" data-toggle="tab" id="previewlink">Preview</a></li>
</ul>
<div class="tab-content">
	<div class="tab-pane active" id="editor">
		<form method="post" class="form">
			{{ form.hidden_tag() }}
			{{ input(form.title, placeholder="Title", class="span7", autocomplete="off") }}
			{{ input(form.body, placeholder="Markdown", class="span7", rows="20") }}
			{{ input(form.tags, placeholder="Tags (comma separated)", class="span7", autocomplete="off") }}
			<div class="form-actions">
        <div class="pull-left">
          <a class="btn" href="#preview" id="previewbtn">Preview</a>
        </div>
				<div class="pull-right">
          <a class="btn" href="{{ url_for('wiki.display', url=page.url) }}">Cancel</a>
					<button class="btn btn-success" type="submit">Save</button>
				</div>
			</div>
		</form>
	</div>
	<div class="tab-pane" id="preview"></div>
</div>
{% endblock content %}

{% block sidebar %}
<h3>Editor How-To</h3>
<p>This editor is <a href="http://daringfireball.net/projects/markdown/">markdown</a> featured.</p>
<pre><code>* I
* am
* a
* list</code></pre>
Turns into:
<ul>
<li>I</li>
<li>am</li>
<li>a</li>
<li>list</li>
</ul>
<p><code>**bold** and *italics*</code> turn into <strong>bold</strong> and <em>italics</em>. Very easy!</p>
<p>Create links with <code>[NoTube](http://www.notube.com)</code>. They turn into <a href="http://www.notube.com">NoTube</a>.</p>
<p>Headers are as follows:</p>
<pre><code># Level 1
## Level 2
### Level 3</code></pre>
<p></p>

{% endblock sidebar %}

{% block postscripts -%}
{{ super() }}
$('#previewlink').on('click', function() {
	var $form = $('.form');
  var $inputs = $form.find('input, textarea, button');
  var $pre = $('#preview');
  var bodycontent = 'title: preview\n\n' + $form.find('textarea').val();
  $inputs.prop('disabled', true);
  $pre.removeClass('alert').removeClass('alert-error').html("Loading...");
  $.ajax({
    url: "{{ url_for('wiki.preview') }}",
    type: "POST",
    data: { body: bodycontent },
    success: function(msg) {
      $pre.html(msg);
      console.log(msg);
    },
    error: function() {
			$pre.addClass('alert').addClass('alert-error');
      $pre.html('There was a problem with the preview.');
    },
    complete: function() {
      $inputs.prop('disabled', false);
    }
  });
});
$('#previewbtn').on('click', function(event) {
	event.preventDefault();
	$('#previewlink').click();
});
{%- endblock postscripts %}

wiki/web/templates/helpers.html
{% macro input(field) -%}
	<div class="control-group {% if field.errors %}error{% endif %}">
		{% if field.type == 'BooleanField' %}
			<div class="controls">
				<label for="{{ field.name }}" class="checkbox">
					{{ field(**kwargs) }}
					{{ field.label.text }}
				</label>
			</div>
		{% else %}
			<label for="{{ field.name }}" class="control-label">{{ field.label.text }}</label>
			<div class="controls">
				{{ field(**kwargs) }}
				{% if field.errors %}
					<div>
						{% for error in field.errors %}
							<span class="help-inline">
								{{ error }}
							</span>
						{% endfor %}
					</div>
				{% endif %}
			</div>
		{% endif %}
	</div>
{%- endmacro %}

wiki/web/templates/home.html
{% extends "base.html" %}
{% block title -%}
	Welcome to your new wiki!
{% endblock title %}

{% block content %}
<p>You did not create any content yet. Your wiki recommends you, to do so now, as every user will see this page first, and you would want to make a good impression, wouldn't you?</p>
<p><a href="{{ url_for('wiki.edit', url='home') }}" class="btn btn-success">Create a homepage</a></p>
{% endblock %}

wiki/web/templates/index.html
{% extends "base.html" %}

{% block title %}Page Index{% endblock title %}

{% block content %}
{% if pages %}
	<table class="table">
		<thead>
			<tr>
				<th>Title</th>
				<th>URL</th>
			</tr>
		</thead>
		<tbody>
			{% for page in pages %}
				<tr>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.title }}</a></td>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.url }}</a></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% else %}
	<p>There are no pages yet.</p>
{% endif %}
{% endblock content %}

{% block sidebar %}
<ul class="nav nav-tabs nav-stacked">
	<li><a href="{{ url_for('wiki.create') }}">New Page</a></li>
	<li><a href="{{ url_for('wiki.tags') }}">Tag List</a></li>
	<li><a href="{{ url_for('wiki.search') }}">Search</a></li>
</ul>
{% endblock sidebar %}

wiki/web/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock title %}

{% block content %}
<form class="form form-inline" method="POST">
	{{ form.hidden_tag() }}
	{{ form.name(placeholder='Username') }}
	{{ form.password(placeholder='Password') }}
	<input type="submit" class="btn btn-primary" value="Login">
</form>
{% endblock content %}

wiki/web/templates/move.html
{% extends "base.html" %}

{% block title %}Move a page{% endblock title %}
{% block content %}
<form method="POST" class="form-inline">
    {{ form.hidden_tag() }}
    {{ input(form.url, placeholder="New URL of the page", autocomplete="off") }}
    <input type="submit" class="btn btn-success" value="Create">
</form>
{% endblock content %}

{% block sidebar %}
<p class="alert alert-success">Be careful, the old url will be invalid immediately!</p>
{% endblock sidebar %}

wiki/web/templates/page.html
{% extends "base.html" %}

{% block title %}
	{{ page.title }}
{% endblock title %}

{% block content %}
  <div id="confirmDelete" class="modal hide fade" aria-hidden="true">
    <div class="modal-header">
      <h3>Are you sure?</h3>
    </div>
    <div class="modal-body">
      <p>Are you sure you want to delete {{ page.title }}?  This cannot be undone.</p>
    </div>
    <div class="modal-footer">
      <a href="#" class="btn" data-dismiss="modal" aria-hidden="true">No</a>
      <a href="{{ url_for('wiki.delete', url=page.url) }}" class="btn btn-danger">Yes, delete.</a>
    </div>
  </div>
	{{ page }}
{% endblock content %}

{% block sidebar %}
{% if page.tags %}
<h3>Tags</h3>
  <ul>
      {% for tag in page.tags.split(',') %}
        <li><a href="{{ url_for('wiki.tag', name=tag.strip()) }}">{{ tag|trim }}</a></li>
      {% endfor %}
  </ul>
{% endif %}
<h3>Actions</h3>
<ul class="nav nav-tabs nav-stacked">
	<li><a href="{{ url_for('wiki.edit', url=page.url) }}">Edit</a></li>
  <li><a href="{{ url_for('wiki.move', url=page.url) }}">Move</a></li>
  <li><a href="#confirmDelete" data-toggle="modal" class="text-error">Delete</a></li>
</ul>
{% endblock sidebar %}

wiki/web/templates/search.html
{% extends "base.html" %}

{% block title %}
{% if search %}
	Results for "{{ search }}"
{% else %}
	Search
{% endif %}
{% endblock title %}

{% block content %}
<div class="row">
	<div class="span8 offset1">
		<form class="form-inline well" method="POST">
			{{ form.hidden_tag() }}
			{{ form.term(placeholder='Search for.. (regex accepted)', autocomplete="off") }}
            {{ form.ignore_case() }} Ignore Case
			<input type="submit" class="btn btn-success pull-right" value="Search!">
		</form>
	</div>
</div>

{% if search %}
	{% if results %}
		<ul>
			{% for result in results %}
				<li><a href="{{ url_for('wiki.display', url=result.url) }}">{{ result.title }}</a></li>
			{% endfor %}
		</ul>
	{% else %}
		<p>No results for your search.</p>
	{% endif %}
{% endif %}
{% endblock content %}

wiki/web/templates/tag.html
{% extends "base.html" %}

{% block title %}Pages tagged {{ tag }}{% endblock title %}

{% block content %}
{% if pages %}
	<table class="table">
		<thead>
			<tr>
				<th>Title</th>
				<th>URL</th>
			</tr>
		</thead>
		<tbody>
			{% for page in pages %}
				<tr>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.title }}</a></td>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.url }}</a></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% else %}
	<p>There are no pages tagged {{ tag }}.</p>
{% endif %}
{% endblock content %}

wiki/web/templates/tags.html
{% extends "base.html" %}

{% block title %}Index by Tags{% endblock title %}

{% block content %}
{% if tags %}
	<table class="table">
		<thead>
			<tr>
				<th>Tag</th>
				<th>Number of Articles</th>
			</tr>
		</thead>
		<tbody>
			{% for tag, pages in tags|dictsort %}
				<tr>
					<td><a href="{{ url_for('wiki.tag', name=tag) }}">{{ tag }}</a></td>
					<td>{{ pages|length }}</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% else %}
	<p>There are no tags in use so far.</p>
{% endif %}
{% endblock content %}